function []= Coder(shooting,continuation,N,dimx,dimu,dimec,dimic,TVP,TVP_f,Xk,Uk,...
    Lmdk,Muk,fxu,Gxu,Cxu,Lk,Phi,R_value,Kmax,errtol,iter_out)
% This is the Coder function of MPsee toolbox by S. Tajeddin,
% This is the main function that generates relative codes and functions for
% nonlinear model predictive controller
% This code comes with no guarantee or warranty of any kind
%% ########################################################################
%  ##################     SINGLE-SHOOTING      ############################
%  ########################################################################
if strcmp(shooting,'single')
    %--------------------------------------------------------------
    Hk=Lk+fxu'*Lmdk+Gxu'*Muk;
    Hxk=gradient(Hk,Xk);
    Huk=gradient(Hk,Uk);
    % ---------------outputing the results--------------
    file4=fopen('FxU.m','w');
    formatspec=['function Fvector = FxU(Xvector,TVP,TVP_f,Uvector,con)'...
        '\nN=%d;\ndimu=%d;\ndimec=%d;\ndimic=%d;\ndimx=%d;'...
        '\ncoder.allowpcode(''plain'');\n'];
    fprintf(file4,formatspec,N,dimu,dimec,dimic,dimx);
    for i=1:length(TVP_f)
        formatspec=['%s=TVP_f(%d);\n'];
        fprintf(file4,formatspec,char(TVP_f(i)),i);
    end
    formatspec=['Fvector=zeros(%d,1);\n'];
    fprintf(file4,formatspec,N*(dimu+dimec));
    
    
    formatspec=['X=zeros(dimx,N+1);\n'...
        'Lmd=zeros(dimx,N+1);\n'...
        'lmdN=zeros(dimx,1);\n'...
        'X(:,1)=Xvector;\n'...
        'for i=2:N+1\n'...
        '    Xk=X(:,i-1);\n'...
        '    Uk=Uvector((i-2)*(dimec+dimu)+1:(i-1)*(dimec+dimu));\n'...
        '    tau=(i-1);\n'...
        '    X(:,i)=X(:,i-1)+dt*f(Xk,TVP,TVP_f,Uk,tau);\n'...
        'end\n'];
    fprintf(file4,formatspec);
    
    lmdN=gradient(Phi,Xk);
    for i=1:length(Xk)
        formatspec=['Xk%d=X(%d,N+1);\n'];
        fprintf(file4,formatspec,i,i);
    end
    for i=1:length(lmdN)
        formatspec=['lmdN(%d)=%s;\n'];
        fprintf(file4,formatspec,i,char(lmdN(i)));
    end
    formatspec=['Lmd(:,N+1)=lmdN'';\n'...
        'if nargin == 5\n'...
        '    for i=N:-1:1\n'...
        '        Xk=X(:,i);\n'...
        '        Uk=Uvector((i-1)*(dimec+dimu)+1:(i)*(dimec+dimu));\n'...
        '        tau=i;\n'...
        '        Lmd(:,i)=Lmd(:,i+1)+dt*dHdx(Xk,TVP,TVP_f,Uk,tau,Lmd(:,i+1), con);\n'...
        '    end\n'...
        '    for i=1:N\n'...
        '        Xk=X(:,i);\n'...
        '        Uk=Uvector((i-1)*(dimec+dimu)+1:(i)*(dimec+dimu));\n'...
        '        Lmdk=Lmd(:,i+1);\n'...
        '        tau=i;\n'...
        '        Fvector((i-1)*dimu+1:(i)*(dimu),:)=dHdu(Xk,TVP,TVP_f,Uk,tau,Lmdk,con);\n'...
        '    end\n'...
        'else\n'...
        '    for i=N:-1:1\n'...
        '        Xk=X(:,i);\n'...
        '        Uk=Uvector((i-1)*(dimec+dimu)+1:(i)*(dimec+dimu));\n'...
        '        tau=i;\n'...
        '        Lmd(:,i)=Lmd(:,i+1)+dt*dHdx(Xk,TVP,TVP_f,Uk,tau,Lmd(:,i+1));\n'...
        '    end\n'...
        '    for i=1:N\n'...
        '        Xk=X(:,i);\n'...
        '        Uk=Uvector((i-1)*(dimec+dimu)+1:(i)*(dimec+dimu));\n'...
        '        Lmdk=Lmd(:,i+1);\n'...
        '        tau=i;\n'...
        '        Fvector((i-1)*dimu+1:(i)*(dimu),:)=dHdu(Xk,TVP,TVP_f,Uk,tau,Lmdk);\n'...
        '    end\n'...
        'end\n'];
    fprintf(file4,formatspec);
    
    %--------------cxu--------------
    file0=fopen('CxU.m','w');
    formatspec=['function y = CxU(x,TVP,TVP_f,u,tau)\n'];
    fprintf(file0,formatspec);
    for i=1:length(TVP)
        formatspec=['%s=TVP(%d,tau);\n'];
        fprintf(file0,formatspec,char(TVP(i)),i);
    end
    for i=1:length(TVP_f)
        formatspec=['%s=TVP_f(%d);\n'];
        fprintf(file0,formatspec,char(TVP_f(i)),i);
    end
    for i=1:length(Xk)
        formatspec=['Xk%d=x(%d);\n'];
        fprintf(file0,formatspec,i,i);
    end
    for i=1:length(Uk)
        formatspec=['Uk%d=u(%d);\n'];
        fprintf(file0,formatspec,i,i);
    end
    formatspec=['y=zeros(%d,1);\n'];
    fprintf(file0,formatspec,length(Cxu));
    for i=1:length(Cxu)
        formatspec=['y(%d)=%s;\n'];
        fprintf(file0,formatspec,i,char(Cxu(i)));
    end
    
    %--------------fxu--------------
    file1=fopen('f.m','w');
    formatspec=['function y = f(x,TVP,TVP_f,u,tau)\n'];
    fprintf(file1,formatspec);
    for i=1:length(TVP)
        formatspec=['%s=TVP(%d,tau);\n'];
        fprintf(file1,formatspec,char(TVP(i)),i);
    end
    for i=1:length(TVP_f)
        formatspec=['%s=TVP_f(%d);\n'];
        fprintf(file1,formatspec,char(TVP_f(i)),i);
    end
    for i=1:length(Xk)
        formatspec=['Xk%d=x(%d);\n'];
        fprintf(file1,formatspec,i,i);
    end
    for i=1:length(Uk)
        formatspec=['Uk%d=u(%d);\n'];
        fprintf(file1,formatspec,i,i);
    end
    
    formatspec=['y=zeros(%d,1);\n'];
    fprintf(file1,formatspec,length(fxu));
    for i=1:length(fxu)
        formatspec=['y(%d)=%s;\n'];
        fprintf(file1,formatspec,i,char(fxu(i)));
    end
    %--------------Hx--------------
    file2=fopen('dHdx.m','w');
    formatspec=['function y = dHdx(x,TVP,TVP_f,u,tau,lmd,Con)\n'];
    fprintf(file2,formatspec);
    for i=1:length(TVP)
        formatspec=['%s=TVP(%d,tau);\n'];
        fprintf(file2,formatspec,char(TVP(i)),i);
    end
    for i=1:length(TVP_f)
        formatspec=['%s=TVP_f(%d);\n'];
        fprintf(file2,formatspec,char(TVP_f(i)),i);
    end
    for i=1:length(Xk)
        formatspec=['Xk%d=x(%d);\n'];
        fprintf(file2,formatspec,i,i);
    end
    for i=1:length(Uk)
        formatspec=['Uk%d=u(%d);\n'];
        fprintf(file2,formatspec,i,i);
    end
    if Muk~=0
        for i=1:length(Muk)
            formatspec=['Muk%d=u(%d);\n'];
            fprintf(file2,formatspec,i,dimu+i);
        end
    end
    for i=1:length(Lmdk)
        formatspec=['Lmdk%d=lmd(%d);\n'];
        fprintf(file2,formatspec,i,i);
    end
    formatspec=['y=zeros(%d,1);\n'];
    fprintf(file2,formatspec,length(Hxk));
    %---
    formatspec=['if nargin == 7\n'...
        '    con=Con(:,tau);\n'];
    fprintf(file2,formatspec);
    for i=1:dimic
        formatspec=['    if con(%d)>0\n'...
            '        r%d=%d;\n'...
            '    else\n'...
            '        r%d=0;\n'...
            '    end\n'];
        fprintf(file2,formatspec,i,i,R_value(i),i);
    end
    formatspec=['else\n'];
    fprintf(file2,formatspec);
    for i=1:dimic
        formatspec=['    r%d=0;\n'];
        fprintf(file2,formatspec,i);
    end
    formatspec=['end\n'];
    fprintf(file2,formatspec);
    %---
    for i=1:length(Hxk)
        formatspec=['y(%d)=%s;\n'];
        fprintf(file2,formatspec,i,char(Hxk(i)));
    end
    
    %--------------Hu--------------
    file3=fopen('dHdu.m','w');
    formatspec=['function y = dHdu(x,TVP,TVP_f,u,tau,lmd,Con)\n'];
    fprintf(file3,formatspec);
    for i=1:length(TVP)
        formatspec=['%s=TVP(%d,tau);\n'];
        fprintf(file3,formatspec,char(TVP(i)),i);
    end
    for i=1:length(TVP_f)
        formatspec=['%s=TVP_f(%d);\n'];
        fprintf(file3,formatspec,char(TVP_f(i)),i);
    end
    for i=1:length(Xk)
        formatspec=['Xk%d=x(%d);\n'];
        fprintf(file3,formatspec,i,i);
    end
    for i=1:length(Uk)
        formatspec=['Uk%d=u(%d);\n'];
        fprintf(file3,formatspec,i,i);
    end
    if Muk~=0
        for i=1:length(Muk)
            formatspec=['Muk%d=u(%d);\n'];
            fprintf(file3,formatspec,i,dimu+i);
        end
    end
    for i=1:length(Lmdk)
        formatspec=['Lmdk%d=lmd(%d);\n'];
        fprintf(file3,formatspec,i,i);
    end
    %---
    formatspec=['if nargin == 7\n'...
        '    con=Con(:,tau);\n'];
    fprintf(file3,formatspec);
    for i=1:dimic
        formatspec=['    if con(%d)>0\n'...
            '        r%d=%d;\n'...
            '    else\n'...
            '        r%d=0;\n'...
            '    end\n'];
        fprintf(file3,formatspec,i,i,R_value(i),i);
    end
    formatspec=['else\n'];
    fprintf(file3,formatspec);
    for i=1:dimic
        formatspec=['    r%d=0;\n'];
        fprintf(file3,formatspec,i);
    end
    formatspec=['end\n'];
    fprintf(file3,formatspec);
    %---
    formatspec=['y=zeros(%d,1);\n'];
    fprintf(file3,formatspec,length(Huk));
    for i=1:length(Huk)
        formatspec=['y(%d)=%s;\n'];
        fprintf(file3,formatspec,i,char(Huk(i)));
    end
    %% ########################################################################
    % #################   Run-Time NMPC Builder   #############################
    % #########################################################################
    if strcmp(continuation,'no')
        file10=fopen('NMPC.m','w');
        formatspec=['function [dU,U,Control] = NMPC(dU0,U0,x0,TVP,TVP_f)\ncoder.allowpcode(''plain'');'...
            '\nKmax=%d;\nerrtol=%d;\ndimic=%d;\niteration_out=%d;\ndimu=%d;\n'];
        fprintf(file10,formatspec,Kmax,errtol,dimic,iter_out,dimu);
        if dimic>0            
        formatspec=['TVP=TVP'';\n'...
            'N=length(TVP);\n'...
            'dt=TVP_f(end);\n'...
            'params=[errtol, Kmax];\n'...
            's=0;\n'...
            'xk=x0;\n'...
            'Con=zeros(dimic,N);\n'...
            'for i=1:N\n'...
            'Uk=U0(dimu*(i-1)+1:dimu*i);\n'...
            'Xdot=f(xk,TVP,TVP_f,Uk,i);\n'...
            'xk=xk+dt*Xdot;\n'...
            'Con(:,i)=CxU(xk,TVP,TVP_f,Uk,i);\n'...
            's=s+sum(Con(:,i)>0);\n'...
            'end\n'...
            'if s>0\n'...
            'f0= FxU(x0, TVP,TVP_f, U0,Con);\n'...
            'dU=fdgmres(f0, x0, TVP,TVP_f, U0, params,dU0,Con);\n'...
            'U=U0+dU;\n'...
            'else\n'...
            'f0= FxU(x0, TVP,TVP_f, U0);\n'...
            'dU=fdgmres(f0, x0, TVP,TVP_f, U0, params,dU0);\n'...
            'U=U0+dU;\n'...
            'end\n'...
            'for rep=1:iteration_out\n'...
            's=0;\n'...
            'xk=x0;\n'...
            'Con=zeros(dimic,N);\n'...
            'for i=1:N\n'...
            'Uk=U(dimu*(i-1)+1:dimu*i);\n'...
            'Xdot=f(xk,TVP,TVP_f,Uk,i);\n'...
            'xk=xk+dt*Xdot;\n'...
            'Con(:,i)=CxU(xk,TVP,TVP_f,Uk,i);\n'...
            's=s+sum(Con(:,i)>0);\n'...
            'end\n'...
            'if s>0\n'...
            'f0= FxU(x0, TVP,TVP_f, U,Con);\n'...
            'dU=fdgmres(f0,x0,TVP,TVP_f,U,params,dU,Con);\n'...
            'U=U+dU;\n'...
            'else\n'...
            'f0= FxU(x0,TVP,TVP_f,U);\n'...
            'dU=fdgmres(f0,x0,TVP,TVP_f,U,params,dU);\n'...
            'U=U+dU;\n'...
            'end\n'...
            'end\n'...
            'Control=U(1:dimu);\n'];
        else
            formatspec=['TVP=TVP'';\n'...
            'N=length(TVP);\n'...
            'dt=TVP_f(end);\n'...
            'params=[errtol, Kmax];\n'...
            'f0= FxU(x0, TVP,TVP_f, U0);\n'...
            'dU=fdgmres(f0, x0, TVP,TVP_f, U0, params,dU0);\n'...
            'U=U0+dU;\n'...
            'for rep=1:iteration_out\n'...
            'f0= FxU(x0,TVP,TVP_f,U);\n'...
            'dU=fdgmres(f0,x0,TVP,TVP_f,U,params,dU);\n'...
            'U=U+dU;\n'...
            'end\n'...
            'Control=U(1:dimu);\n'];
        end
        fprintf(file10,formatspec);
        
    elseif strcmp(continuation,'yes')
        file10=fopen('NMPC.m','w');
        formatspec=['function [dU,U,Control] = NMPC(dU0,U0,x0,x1,TVP,TVP_f)\ncoder.allowpcode(''plain'');'...
            '\nKmax=%d;\nerrtol=%d;\ndimic=%d;\niteration_out=%d;\ndimu=%d;\n'];
        fprintf(file10,formatspec,Kmax,errtol,dimic,iter_out,dimu);
        if dimic>0
        formatspec=['TVP=TVP'';\n'...
            'N=length(TVP);\n'...
            'dt=TVP_f(end);\n'...
            'params=[errtol, Kmax];\n'...
            'dx=(x0-x1);\n'...
            's=0;\n'...
            'xk=x0;\n'...
            'Con=zeros(dimic,N);\n'...
            'for i=1:N\n'...
            'Uk=U0(dimu*(i-1)+1:dimu*i);\n'...
            'Xdot=f(xk,TVP,TVP_f,Uk,i);\n'...
            'xk=xk+dt*Xdot;\n'...
            'Con(:,i)=CxU(xk,TVP,TVP_f,Uk,i);\n'...
            's=s+sum(Con(:,i)>0);\n'...
            'end\n'...
            'if s>0\n'...
            'f0= FxU(x0, TVP,TVP_f, U0,Con);\n'...
            'dU=C_FDGMRES(f0, x0, TVP,TVP_f, U0, params,dU0,dx,Con);\n'...
            'U=U0+dU;\n'...
            'else\n'...
            'f0= FxU(x0, TVP,TVP_f, U0);\n'...
            'dU=C_FDGMRES(f0, x0, TVP,TVP_f, U0, params,dU0,dx);\n'...
            'U=U0+dU;\n'...
            'end\n'...
            'for rep=1:iteration_out\n'...
            's=0;\n'...
            'xk=x0;\n'...
            'Con=zeros(dimic,N);\n'...
            'for i=1:N\n'...
            'Uk=U(dimu*(i-1)+1:dimu*i);\n'...
            'Xdot=f(xk,TVP,TVP_f,Uk,i);\n'...
            'xk=xk+dt*Xdot;\n'...
            'Con(:,i)=CxU(xk,TVP,TVP_f,Uk,i);\n'...
            's=s+sum(Con(:,i)>0);\n'...
            'end\n'...
            'if s>0\n'...
            'f0= FxU(x0, TVP,TVP_f, U,Con);\n'...
            'dU=C_FDGMRES(f0, x0, TVP,TVP_f, U, params,dU,dx,Con);\n'...
            'U=U+dU;\n'...
            'else\n'...
            'f0= FxU(x0,TVP,TVP_f,U);\n'...
            'dU=C_FDGMRES(f0, x0, TVP,TVP_f, U, params,dU,dx);\n'...
            'U=U+dU;\n'...
            'end\n'...
            'end\n'...
            'Control=U(1:dimu);\n'];
        else
            formatspec=['TVP=TVP'';\n'...
            'N=length(TVP);\n'...
            'dt=TVP_f(end);\n'...
            'params=[errtol, Kmax];\n'...
            'dx=(x0-x1);\n'...
            'f0= FxU(x0, TVP,TVP_f, U0);\n'...
            'dU=C_FDGMRES(f0, x0, TVP,TVP_f, U0, params,dU0,dx);\n'...
            'U=U0+dU;\n'...
            'for rep=1:iteration_out\n'...
            'f0= FxU(x0,TVP,TVP_f,U);\n'...
            'dU=C_FDGMRES(f0, x0, TVP,TVP_f, U, params,dU,dx);\n'...
            'U=U+dU;\n'...
            'end\n'...
            'Control=U(1:dimu);\n'];
        end
            
        fprintf(file10,formatspec);
    else
        error('Invalid continuation setting.')
    end
    
    %% ####################################################################
    % ########################   MULTIPLE-SHOOTING   ######################
    % #####################################################################
elseif strcmp(shooting,'multiple')
    
    U_size=N*(dimu+dimec+dimx+dimx);
    %--------------------------------------------------------------
    Hk=Lk+fxu'*Lmdk+Gxu'*Muk;
    Hxk=gradient(Hk,Xk);
    Huk=gradient(Hk,Uk);
    lmdN=gradient(Phi,Xk);
    
    % ---------------outputing the results--------------
    if dimec==0
        
        file0=fopen('FxU.m','w');
        formatspec=['function Fvector = FxU(Xvector,TVP,TVP_f,Uvector,con)\nN=%d;\ndimu=%d;\ndimec=%d;\ndimic=%d;\ndimx=%d;\n'...
            'coder.allowpcode(''plain'');\n'];
        fprintf(file0,formatspec,N,dimu,dimec,dimic,dimx);
        for i=1:length(TVP_f)
            formatspec=['%s=TVP_f(%d);\n'];
            fprintf(file0,formatspec,char(TVP_f(i)),i);
        end
        formatspec=['Fvector=zeros(%d,1);\n'];
        fprintf(file0,formatspec,N*(dimu+dimec+dimx+dimx));
        
        formatspec=['U=Uvector(1:N*dimu);\n'...
            'Mu=0;\n'...
            'X=[Xvector;Uvector(N*(dimu+dimec)+1:N*(dimu+dimec+dimx))];\n'...
            'Lmd=Uvector(N*(dimu+dimec+dimx)+1:N*(dimu+dimec+dimx+dimx));\n'];
        fprintf(file0,formatspec);
        
        for i=1:length(Xk)
            formatspec=['Xk%d=X((N-1)*(dimx)+%d);\n'];
            fprintf(file0,formatspec,i,i);
        end
        formatspec=['lmdN=zeros(dimx,1);\n'];
        fprintf(file0,formatspec);
        for i=1:length(lmdN)
            formatspec=['lmdN(%d,1)=%s;\n'];
            fprintf(file0,formatspec,i,char(lmdN(i)));
        end
        formatspec=['Lmd=[Lmd;lmdN];\n'];
        fprintf(file0,formatspec);
        
        formatspec=['if nargin == 5\n'...
            '    for i=1:N-1\n'...
            '        Uk=U((i-1)*(dimu)+1:(i)*(dimu));\n'...
            '        Uk1=U((i)*(dimu)+1:(i+1)*(dimu));\n'...
            '        Muk=Mu;\n'...
            '        Muk1=Mu;\n'...
            '        Xk=X((i-1)*(dimx)+1:(i)*(dimx));\n'...
            '        Xk1=X((i)*(dimx)+1:(i+1)*(dimx));\n'...
            '        Lmdk=Lmd((i-1)*(dimx)+1:(i)*(dimx));\n'...
            '        Lmdk1=Lmd((i)*(dimx)+1:(i+1)*(dimx));\n'...
            '        Fvector((i-1)*dimu+1:(i)*(dimu),:)=dHdu(Xk,Uk,Muk,Lmdk,TVP,TVP_f,i,con);\n'...
            '        Fvector(N*dimu+(i-1)*dimx+1:N*dimu+(i)*(dimx),:)=Xk1-Xk-dt*f(Xk,Uk,TVP,TVP_f,i);\n'...
            '        Fvector(N*(dimu+dimx)+(i-1)*dimx+1:N*(dimu+dimx)+(i)*(dimx),:)=Lmdk-Lmdk1-dt*dHdx(Xk1,Uk1,Muk1,Lmdk1,TVP,TVP_f,i+1,con);\n'...
            '    end\n'...
            'Uk=U((N-1)*(dimu)+1:(N)*(dimu));\n'...
            'Muk=Mu;\n'...
            'Xk=X((N-1)*(dimx)+1:(N)*(dimx));\n'...
            'Xk1=X((N)*(dimx)+1:(N+1)*(dimx));\n'...
            'Lmdk=Lmd((N-1)*(dimx)+1:(N)*(dimx));\n'...
            'Lmdk1=Lmd((N)*(dimx)+1:(N+1)*(dimx));\n'...
            'Fvector((N-1)*dimu+1:(N)*(dimu),:)=dHdu(Xk,Uk,Muk,Lmdk,TVP,TVP_f,N,con);\n'...
            'Fvector(N*dimu+(N-1)*dimx+1:N*dimu+(N)*(dimx),:)=Xk1-Xk-dt*f(Xk,Uk,TVP,TVP_f,N);\n'...
            'Fvector(N*(dimu+dimx)+(N-1)*dimx+1:N*(dimu+dimx)+(N)*(dimx),:)=Lmdk-Lmdk1;\n'...
            'else\n'...
            '    for i=1:N-1\n'...
            '        Uk=U((i-1)*(dimu)+1:(i)*(dimu));\n'...
            '        Uk1=U((i)*(dimu)+1:(i+1)*(dimu));\n'...
            '        Muk=Mu;\n'...
            '        Muk1=Mu;\n'...
            '        Xk=X((i-1)*(dimx)+1:(i)*(dimx));\n'...
            '        Xk1=X((i)*(dimx)+1:(i+1)*(dimx));\n'...
            '        Lmdk=Lmd((i-1)*(dimx)+1:(i)*(dimx));\n'...
            '        Lmdk1=Lmd((i)*(dimx)+1:(i+1)*(dimx));\n'...
            '        Fvector((i-1)*dimu+1:(i)*(dimu),:)=dHdu(Xk,Uk,Muk,Lmdk,TVP,TVP_f,i);\n'...
            '        Fvector(N*dimu+(i-1)*dimx+1:N*dimu+(i)*(dimx),:)=Xk1-Xk-dt*f(Xk,Uk,TVP,TVP_f,i);\n'...
            '        Fvector(N*(dimu+dimx)+(i-1)*dimx+1:N*(dimu+dimx)+(i)*(dimx),:)=Lmdk-Lmdk1-dt*dHdx(Xk1,Uk1,Muk1,Lmdk1,TVP,TVP_f,i+1);\n'...
            '    end\n'...
            'Uk=U((N-1)*(dimu)+1:(N)*(dimu));\n'...
            'Muk=Mu;\n'...
            'Xk=X((N-1)*(dimx)+1:(N)*(dimx));\n'...
            'Xk1=X((N)*(dimx)+1:(N+1)*(dimx));\n'...
            'Lmdk=Lmd((N-1)*(dimx)+1:(N)*(dimx));\n'...
            'Lmdk1=Lmd((N)*(dimx)+1:(N+1)*(dimx));\n'...
            'Fvector((N-1)*dimu+1:(N)*(dimu),:)=dHdu(Xk,Uk,Muk,Lmdk,TVP,TVP_f,N);\n'...
            'Fvector(N*dimu+(N-1)*dimx+1:N*dimu+(N)*(dimx),:)=Xk1-Xk-dt*f(Xk,Uk,TVP,TVP_f,N);\n'...
            'Fvector(N*(dimu+dimx)+(N-1)*dimx+1:N*(dimu+dimx)+(N)*(dimx),:)=Lmdk-Lmdk1;\n'...
            'end\n'];
        fprintf(file0,formatspec);
        
    else
        
        file0=fopen('FxU.m','w');
        formatspec=['function Fvector = FxU(Xvector,TVP,TVP_f,Uvector,con)\nN=%d;\ndimu=%d;\ndimec=%d;\ndimic=%d;\ndimx=%d;\n'...
            'coder.allowpcode(''plain'');\n'];
        fprintf(file0,formatspec,N,dimu,dimec,dimic,dimx);
        for i=1:length(TVP_f)
            formatspec=['%s=TVP_f(%d);\n'];
            fprintf(file0,formatspec,char(TVP_f(i)),i);
        end
        formatspec=['Fvector=zeros(%d,1);\n'];
        fprintf(file0,formatspec,N*(dimu+dimec+dimx+dimx));
        
        formatspec=['U=Uvector(1:N*dimu);\n'...
            'Mu=Uvector(N*dimu+1:N*(dimu+dimec));\n'...
            'X=[Xvector;Uvector(N*(dimu+dimec)+1:N*(dimu+dimec+dimx))];\n'...
            'Lmd=Uvector(N*(dimu+dimec+dimx)+1:N*(dimu+dimec+dimx+dimx));\n'];
        fprintf(file0,formatspec);
        
        for i=1:length(Xk)
            formatspec=['Xk%d=X((N-1)*(dimx)+%d);\n'];
            fprintf(file0,formatspec,i,i);
        end
        formatspec=['lmdN=zeros(dimx,1);\n'];
        fprintf(file0,formatspec);
        for i=1:length(lmdN)
            formatspec=['lmdN(%d,1)=%s;\n'];
            fprintf(file0,formatspec,i,char(lmdN(i)));
        end
        formatspec=['Lmd=[Lmd;lmdN];\n'];
        fprintf(file0,formatspec);
        
        formatspec=['if nargin == 5\n'...
            '    for i=1:N-1\n'...
            '        Uk=U((i-1)*(dimu)+1:(i)*(dimu));\n'...
            '        Uk1=U((i)*(dimu)+1:(i+1)*(dimu));\n'...
            '        Muk=Mu((i-1)*(dimec)+1:(i)*(dimec));\n'...
            '        Muk1=Mu((i)*(dimec)+1:(i+1)*(dimec));\n'...
            '        Xk=X((i-1)*(dimx)+1:(i)*(dimx));\n'...
            '        Xk1=X((i)*(dimx)+1:(i+1)*(dimx));\n'...
            '        Lmdk=Lmd((i-1)*(dimx)+1:(i)*(dimx));\n'...
            '        Lmdk1=Lmd((i)*(dimx)+1:(i+1)*(dimx));\n'...
            '        Fvector((i-1)*dimu+1:(i)*(dimu),:)=dHdu(Xk,Uk,Muk,Lmdk,TVP,TVP_f,i,con);\n'...
            '        Fvector(N*dimu+(i-1)*dimec+1:N*dimu+(i)*(dimec),:)=GxU(Xk,Uk,TVP,TVP_f,i);\n'...
            '        Fvector(N*(dimu+dimec)+(i-1)*dimx+1:N*(dimu+dimec)+(i)*(dimx),:)=Xk1-Xk-dt*f(Xk,Uk,TVP,TVP_f,i);\n'...
            '        Fvector(N*(dimu+dimec+dimx)+(i-1)*dimx+1:N*(dimu+dimec+dimx)+(i)*(dimx),:)=Lmdk-Lmdk1-dt*dHdx(Xk1,Uk1,Muk1,Lmdk1,TVP,TVP_f,i+1,con);\n'...
            '    end\n'...
            'Uk=U((N-1)*(dimu)+1:(N)*(dimu));\n'...
            'Muk=Mu((N-1)*(dimec)+1:(N)*(dimec));\n'...
            'Xk=X((N-1)*(dimx)+1:(N)*(dimx));\n'...
            'Xk1=X((N)*(dimx)+1:(N+1)*(dimx));\n'...
            'Lmdk=Lmd((N-1)*(dimx)+1:(N)*(dimx));\n'...
            'Lmdk1=Lmd((N)*(dimx)+1:(N+1)*(dimx));\n'...
            'Fvector((N-1)*dimu+1:(N)*(dimu),:)=dHdu(Xk,Uk,Muk,Lmdk,TVP,TVP_f,N,con);\n'...
            'Fvector(N*dimu+(N-1)*dimec+1:N*dimu+(N)*(dimec),:)=GxU(Xk,Uk,TVP,TVP_f,i);\n'...
            'Fvector(N*dimu+(N-1)*dimx+1:N*dimu+(N)*(dimx),:)=Xk1-Xk-dt*f(Xk,Uk,TVP,TVP_f,N);\n'...
            'Fvector(N*(dimu+dimx)+(N-1)*dimx+1:N*(dimu+dimx)+(N)*(dimx),:)=Lmdk-Lmdk1;\n'...
            'else\n'...
            '    for i=1:N-1\n'...
            '        Uk=U((i-1)*(dimu)+1:(i)*(dimu));\n'...
            '        Uk1=U((i)*(dimu)+1:(i+1)*(dimu));\n'...
            '        Muk=Mu((i-1)*(dimec)+1:(i)*(dimec));\n'...
            '        Muk1=Mu((i)*(dimec)+1:(i+1)*(dimec));\n'...
            '        Xk=X((i-1)*(dimx)+1:(i)*(dimx));\n'...
            '        Xk1=X((i)*(dimx)+1:(i+1)*(dimx));\n'...
            '        Lmdk=Lmd((i-1)*(dimx)+1:(i)*(dimx));\n'...
            '        Lmdk1=Lmd((i)*(dimx)+1:(i+1)*(dimx));\n'...
            '        Fvector((i-1)*dimu+1:(i)*(dimu),:)=dHdu(Xk,Uk,Muk,Lmdk,TVP,TVP_f,i);\n'...
            '        Fvector(N*dimu+(i-1)*dimec+1:N*dimu+(i)*(dimec),:)=GxU(Xk,Uk,TVP,TVP_f,i);\n'...
            '        Fvector(N*(dimu+dimec)+(i-1)*dimx+1:N*(dimu+dimec)+(i)*(dimx),:)=Xk1-Xk-dt*f(Xk,Uk,TVP,TVP_f,i);\n'...
            '        Fvector(N*(dimu+dimec+dimx)+(i-1)*dimx+1:N*(dimu+dimec+dimx)+(i)*(dimx),:)=Lmdk-Lmdk1-dt*dHdx(Xk,Uk,Muk,Lmdk1,TVP,TVP_f,i);\n'...
            '    end\n'...
            'Uk=U((N-1)*(dimu)+1:(N)*(dimu));\n'...
            'Muk=Mu((N-1)*(dimec)+1:(N)*(dimec));\n'...
            'Xk=X((N-1)*(dimx)+1:(N)*(dimx));\n'...
            'Xk1=X((N)*(dimx)+1:(N+1)*(dimx));\n'...
            'Lmdk=Lmd((N-1)*(dimx)+1:(N)*(dimx));\n'...
            'Lmdk1=Lmd((N)*(dimx)+1:(N+1)*(dimx));\n'...
            'Fvector((N-1)*dimu+1:(N)*(dimu),:)=dHdu(Xk,Uk,Muk,Lmdk,TVP,TVP_f,N);\n'...
            'Fvector(N*dimu+(N-1)*dimec+1:N*dimu+(N)*(dimec),:)=GxU(Xk,Uk,TVP,TVP_f,i);\n'...
            'Fvector(N*dimu+(N-1)*dimx+1:N*dimu+(N)*(dimx),:)=Xk1-Xk-dt*f(Xk,Uk,TVP,TVP_f,N);\n'...
            'Fvector(N*(dimu+dimx)+(N-1)*dimx+1:N*(dimu+dimx)+(N)*(dimx),:)=Lmdk-Lmdk1;\n'...
            'end\n'];
        fprintf(file0,formatspec);
    end
    
    %--------------cxu--------------
    file1=fopen('CxU.m','w');
    formatspec=['function y = CxU(x,u,TVP,TVP_f,tau)\n'...
        'coder.allowpcode(''plain'');\n'];
    fprintf(file1,formatspec);
    for i=1:length(TVP)
        formatspec=['%s=TVP(%d,tau);\n'];
        fprintf(file1,formatspec,char(TVP(i)),i);
    end
    for i=1:length(TVP_f)
        formatspec=['%s=TVP_f(%d);\n'];
        fprintf(file1,formatspec,char(TVP_f(i)),i);
    end
    for i=1:length(Xk)
        formatspec=['Xk%d=x(%d);\n'];
        fprintf(file1,formatspec,i,i);
    end
    for i=1:length(Uk)
        formatspec=['Uk%d=u(%d);\n'];
        fprintf(file1,formatspec,i,i);
    end
    formatspec=['y=zeros(%d,1);\n'];
    fprintf(file1,formatspec,length(Cxu));
    for i=1:length(Cxu)
        formatspec=['y(%d)=%s;\n'];
        fprintf(file1,formatspec,i,char(Cxu(i)));
    end
    %formatspec=['y=y'';\n'];
    %fprintf(file0,formatspec);
    
    %--------------fxu--------------
    file2=fopen('f.m','w');
    formatspec=['function y = f(x,u,TVP,TVP_f,tau)\n'...
        'coder.allowpcode(''plain'');\n'];
    fprintf(file2,formatspec);
    for i=1:length(TVP)
        formatspec=['%s=TVP(%d,tau);\n'];
        fprintf(file2,formatspec,char(TVP(i)),i);
    end
    for i=1:length(TVP_f)
        formatspec=['%s=TVP_f(%d);\n'];
        fprintf(file2,formatspec,char(TVP_f(i)),i);
    end
    for i=1:length(Xk)
        formatspec=['Xk%d=x(%d);\n'];
        fprintf(file2,formatspec,i,i);
    end
    for i=1:length(Uk)
        formatspec=['Uk%d=u(%d);\n'];
        fprintf(file2,formatspec,i,i);
    end
    formatspec=['y=zeros(%d,1);\n'];
    fprintf(file2,formatspec,length(fxu));
    for i=1:length(fxu)
        formatspec=['y(%d)=%s;\n'];
        fprintf(file2,formatspec,i,char(fxu(i)));
    end
    %formatspec=['y=y'';\n'];
    %fprintf(file1,formatspec);
    
    %--------------Hx--------------
    file3=fopen('dHdx.m','w');
    formatspec=['function y = dHdx(x,u,mu,lmd,TVP,TVP_f,tau,Con)\n'...
        'coder.allowpcode(''plain'');\n'];
    fprintf(file3,formatspec);
    for i=1:length(TVP)
        formatspec=['%s=TVP(%d,tau);\n'];
        fprintf(file3,formatspec,char(TVP(i)),i);
    end
    for i=1:length(TVP_f)
        formatspec=['%s=TVP_f(%d);\n'];
        fprintf(file3,formatspec,char(TVP_f(i)),i);
    end
    for i=1:length(Xk)
        formatspec=['Xk%d=x(%d);\n'];
        fprintf(file3,formatspec,i,i);
    end
    for i=1:length(Uk)
        formatspec=['Uk%d=u(%d);\n'];
        fprintf(file3,formatspec,i,i);
    end
    for i=1:length(Muk)
        formatspec=['Muk%d=mu(%d);\n'];
        fprintf(file3,formatspec,i,i);
    end
    for i=1:length(Lmdk)
        formatspec=['Lmdk%d=lmd(%d);\n'];
        fprintf(file3,formatspec,i,i);
    end
    formatspec=['y=zeros(%d,1);\n'];
    fprintf(file3,formatspec,length(Hxk));
    %---
    formatspec=['if nargin == 8\n'...
        '    con=Con(:,tau);\n'];
    fprintf(file3,formatspec);
    for i=1:dimic
        formatspec=['    if con(%d)>0\n'...
            '        r%d=%d;\n'...
            '    else\n'...
            '        r%d=0;\n'...
            '    end\n'];
        fprintf(file3,formatspec,i,i,R_value(i),i);
    end
    formatspec=['else\n'];
    fprintf(file3,formatspec);
    for i=1:dimic
        formatspec=['    r%d=0;\n'];
        fprintf(file3,formatspec,i);
    end
    formatspec=['end\n'];
    fprintf(file3,formatspec);
    %---
    for i=1:length(Hxk)
        formatspec=['y(%d)=%s;\n'];
        fprintf(file3,formatspec,i,char(Hxk(i)));
    end
    %formatspec=['y=y'';\n'];
    %fprintf(file2,formatspec);
    
    %--------------Hu--------------
    file4=fopen('dHdu.m','w');
    formatspec=['function y = dHdu(x,u,mu,lmd,TVP,TVP_f,tau,Con)\n'...
        'coder.allowpcode(''plain'');\n'];
    fprintf(file4,formatspec);
    for i=1:length(TVP)
        formatspec=['%s=TVP(%d,tau);\n'];
        fprintf(file4,formatspec,char(TVP(i)),i);
    end
    for i=1:length(TVP_f)
        formatspec=['%s=TVP_f(%d);\n'];
        fprintf(file4,formatspec,char(TVP_f(i)),i);
    end
    for i=1:length(Xk)
        formatspec=['Xk%d=x(%d);\n'];
        fprintf(file4,formatspec,i,i);
    end
    for i=1:length(Uk)
        formatspec=['Uk%d=u(%d);\n'];
        fprintf(file4,formatspec,i,i);
    end
    for i=1:length(Muk)
        formatspec=['Muk%d=mu(%d);\n'];
        fprintf(file4,formatspec,i,i);
    end
    for i=1:length(Lmdk)
        formatspec=['Lmdk%d=lmd(%d);\n'];
        fprintf(file4,formatspec,i,i);
    end
    %---
    formatspec=['if nargin == 8\n'...
        '    con=Con(:,tau);\n'];
    fprintf(file4,formatspec);
    for i=1:dimic
        formatspec=['    if con(%d)>0\n'...
            '        r%d=%d;\n'...
            '    else\n'...
            '        r%d=0;\n'...
            '    end\n'];
        fprintf(file4,formatspec,i,i,R_value(i),i);
    end
    formatspec=['else\n'];
    fprintf(file4,formatspec);
    for i=1:dimic
        formatspec=['    r%d=0;\n'];
        fprintf(file4,formatspec,i);
    end
    formatspec=['end\n'];
    fprintf(file4,formatspec);
    %---
    formatspec=['y=zeros(%d,1);\n'];
    fprintf(file4,formatspec,length(Huk));
    for i=1:length(Huk)
        formatspec=['y(%d)=%s;\n'];
        fprintf(file4,formatspec,i,char(Huk(i)));
    end
    % formatspec=['y=y'';\n'];
    % fprintf(file3,formatspec);
    
    %--------------Gxu--------------
    file5=fopen('GxU.m','w');
    formatspec=['function y = GxU(x,u,TVP,TVP_f,tau)\n'...
        'coder.allowpcode(''plain'');\n'];
    fprintf(file5,formatspec);
    for i=1:length(TVP)
        formatspec=['%s=TVP(%d,tau);\n'];
        fprintf(file5,formatspec,char(TVP(i)),i);
    end
    for i=1:length(TVP_f)
        formatspec=['%s=TVP_f(%d);\n'];
        fprintf(file5,formatspec,char(TVP_f(i)),i);
    end
    for i=1:length(Xk)
        formatspec=['Xk%d=x(%d);\n'];
        fprintf(file5,formatspec,i,i);
    end
    for i=1:length(Uk)
        formatspec=['Uk%d=u(%d);\n'];
        fprintf(file5,formatspec,i,i);
    end
    formatspec=['y=zeros(%d,1);\n'];
    fprintf(file5,formatspec,length(Gxu));
    for i=1:length(Gxu)
        formatspec=['y(%d)=%s;\n'];
        fprintf(file5,formatspec,i,char(Gxu(i)));
    end
    %% ########################################################################
    % #################   Run-Time NMPC Builder   #############################
    % #########################################################################
    if strcmp(continuation,'no')
        file10=fopen('NMPC.m','w');
        formatspec=['function [dU,U,Control] = NMPC(dU0,U0,x0,TVP,TVP_f)\ncoder.allowpcode(''plain'');'...
            '\nKmax=%d;\nerrtol=%d;\ndimic=%d;\niteration_out=%d;\ndimu=%d;\n'];
        fprintf(file10,formatspec,Kmax,errtol,dimic,iter_out,dimu);
        if dimic>0
        formatspec=['TVP=TVP'';\n'...
            'N=length(TVP);\n'...
            'dt=TVP_f(end);\n'...
            'params=[errtol, Kmax];\n'...
            's=0;\n'...
            'xk=x0;\n'...
            'Con=zeros(dimic,N);\n'...
            'for i=1:N\n'...
            'Uk=U0(dimu*(i-1)+1:dimu*i);\n'...
            'Xdot=f(xk,Uk,TVP,TVP_f,i);\n'...
            'xk=xk+dt*Xdot;\n'...
            'Con(:,i)=CxU(xk,Uk,TVP,TVP_f,i);\n'...
            's=s+sum(Con(:,i)>0);\n'...
            'end\n'...
            'if s>0\n'...
            'f0= FxU(x0, TVP,TVP_f, U0,Con);\n'...
            'dU=fdgmres(f0, x0, TVP,TVP_f, U0, params,dU0,Con);\n'...
            'U=U0+dU;\n'...
            'else\n'...
            'f0= FxU(x0, TVP,TVP_f, U0);\n'...
            'dU=fdgmres(f0, x0, TVP,TVP_f, U0, params,dU0);\n'...
            'U=U0+dU;\n'...
            'end\n'...
            'for rep=1:iteration_out\n'...
            's=0;\n'...
            'xk=x0;\n'...
            'Con=zeros(dimic,N);\n'...
            'for i=1:N\n'...
            'Uk=U(dimu*(i-1)+1:dimu*i);\n'...
            'Xdot=f(xk,Uk,TVP,TVP_f,i);\n'...
            'xk=xk+dt*Xdot;\n'...
            'Con(:,i)=CxU(xk,Uk,TVP,TVP_f,i);\n'...
            's=s+sum(Con(:,i)>0);\n'...
            'end\n'...
            'if s>0\n'...
            'f0= FxU(x0, TVP,TVP_f, U,Con);\n'...
            'dU=fdgmres(f0,x0,TVP,TVP_f,U,params,dU,Con);\n'...
            'U=U+dU;\n'...
            'else\n'...
            'f0= FxU(x0,TVP,TVP_f,U);\n'...
            'dU=fdgmres(f0,x0,TVP,TVP_f,U,params,dU);\n'...
            'U=U+dU;\n'...
            'end\n'...
            'end\n'...
            'Control=U(1:dimu);\n'];
        else
            formatspec=['TVP=TVP'';\n'...
            'N=length(TVP);\n'...
            'dt=TVP_f(end);\n'...
            'params=[errtol, Kmax];\n'...
            'f0= FxU(x0, TVP,TVP_f, U0);\n'...
            'dU=fdgmres(f0, x0, TVP,TVP_f, U0, params,dU0);\n'...
            'U=U0+dU;\n'...
            'for rep=1:iteration_out\n'...
            'f0= FxU(x0,TVP,TVP_f,U);\n'...
            'dU=fdgmres(f0,x0,TVP,TVP_f,U,params,dU);\n'...
            'U=U+dU;\n'...
            'end\n'...
            'Control=U(1:dimu);\n'];
        end
            
        fprintf(file10,formatspec);
        
    elseif strcmp(continuation,'yes')
        file10=fopen('NMPC.m','w');
        formatspec=['function [dU,U,Control] = NMPC(dU0,U0,x0,x1,TVP,TVP_f)\ncoder.allowpcode(''plain'');'...
            '\nKmax=%d;\nerrtol=%d;\ndimic=%d;\niteration_out=%d;\ndimu=%d;\n'];
        fprintf(file10,formatspec,Kmax,errtol,dimic,iter_out,dimu);
        if dimic>0
        formatspec=['TVP=TVP'';\n'...
            'N=length(TVP);\n'...
            'dt=TVP_f(end);\n'...
            'params=[errtol, Kmax];\n'...
            'dx=(x0-x1);\n'...
            's=0;\n'...
            'xk=x0;\n'...
            'Con=zeros(dimic,N);\n'...
            'for i=1:N\n'...
            'Uk=U0(dimu*(i-1)+1:dimu*i);\n'...
            'Xdot=f(xk,Uk,TVP,TVP_f,i);\n'...
            'xk=xk+dt*Xdot;\n'...
            'Con(:,i)=CxU(xk,Uk,TVP,TVP_f,i);\n'...
            's=s+sum(Con(:,i)>0);\n'...
            'end\n'...
            'if s>0\n'...
            'f0= FxU(x0, TVP,TVP_f, U0,Con);\n'...
            'dU=C_FDGMRES(f0, x0, TVP,TVP_f, U0, params,dU0,dx,Con);\n'...
            'U=U0+dU;\n'...
            'else\n'...
            'f0= FxU(x0, TVP,TVP_f, U0);\n'...
            'dU=C_FDGMRES(f0, x0, TVP,TVP_f, U0, params,dU0,dx);\n'...
            'U=U0+dU;\n'...
            'end\n'...
            'for rep=1:iteration_out\n'...
            's=0;\n'...
            'xk=x0;\n'...
            'Con=zeros(dimic,N);\n'...
            'for i=1:N\n'...
            'Uk=U(dimu*(i-1)+1:dimu*i);\n'...
            'Xdot=f(xk,Uk,TVP,TVP_f,i);\n'...
            'xk=xk+dt*Xdot;\n'...
            'Con(:,i)=CxU(xk,Uk,TVP,TVP_f,i);\n'...
            's=s+sum(Con(:,i)>0);\n'...
            'end\n'...
            'if s>0\n'...
            'f0= FxU(x0, TVP,TVP_f, U,Con);\n'...
            'dU=C_FDGMRES(f0, x0, TVP,TVP_f, U, params,dU,dx,Con);\n'...
            'U=U+dU;\n'...
            'else\n'...
            'f0= FxU(x0,TVP,TVP_f,U);\n'...
            'dU=C_FDGMRES(f0, x0, TVP,TVP_f, U, params,dU,dx);\n'...
            'U=U+dU;\n'...
            'end\n'...
            'end\n'...
            'Control=U(1:dimu);\n'];
        else
            formatspec=['TVP=TVP'';\n'...
            'N=length(TVP);\n'...
            'dt=TVP_f(end);\n'...
            'params=[errtol, Kmax];\n'...
            'dx=(x0-x1);\n'...
            'f0= FxU(x0, TVP,TVP_f, U0);\n'...
            'dU=C_FDGMRES(f0, x0, TVP,TVP_f, U0, params,dU0,dx);\n'...
            'U=U0+dU;\n'...
            'for rep=1:iteration_out\n'...
            'f0= FxU(x0,TVP,TVP_f,U);\n'...
            'dU=C_FDGMRES(f0, x0, TVP,TVP_f, U, params,dU,dx);\n'...
            'U=U+dU;\n'...
            'end\n'...
            'Control=U(1:dimu);\n'];
        end
        fprintf(file10,formatspec);
    else
        error('Invalid continuation setting.')
    end
else
    error('Invalid shooting method setting.')
end

